include required(classpath("application"))

docker {
  hash-lookup {
    method = "local"
  }
}

backend {
  default = "Local"
  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        include required(classpath("reference_local_provider_config.inc.conf"))
        root = "/mnt/data1/zhangpf/code2workspace/results/wdl_result/cromwell-executions"
      }
    }
  }
}
